(require 'ergoemacs-mode)
(ergoemacs-ignore-prev-global)
(setq ergoemacs-theme nil)
(ergoemacs-mode +1)
(evil-emacs-state)
(setq ergoemacs-repeat-smart-punctuation 'all)
(setq ergoemacs-repeat-shortcut-keymap 'all)
(setq ergoemacs-repeat-movement-commands 'nil)
(setq ergoemacs-repeat-movement-commands 'all)
(defalias 'evil-insert-state 'evil-emacs-state)
(provide 'ergo)
