;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        TeX-insert-sub-or-superscript
        TeX-newline
        back-to-indentation-visual-or-beginning
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        cua-copy-region
        cua-cut-region
        cua-paste
        easy-kill
        end-of-visual-line-or-end
        evil-backward-char
        evil-cycle-spacing
        evil-delete-backward-char-and-join
        evil-delete-backward-word-smart
        evil-forward-char
        evil-next-line
        evil-next-visual-line
        evil-previous-line
        evil-previous-visual-line
        haskell-indentation-common-electric-command
        indent-for-tab-command
        julia-latexsub-or-indent
        ps-mode-backward-delete-char
        julia-latexsub-or-indent
        sp-backward-sexp
        sp-backward-unwrap-sexp
        sp-down-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-sexp
        sp-remove-active-pair-overlay
        ))

(setq mc/cmds-to-run-once
      '(
        TeX-command-master
        evil-mouse-drag-region
        evil-normal-state
        handle-select-window
        hydra/projectile-tools/body
        ))
