;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-visual-or-beginning
        end-of-visual-line-or-end
        evil-delete-backward-word-smart
        sp-backward-sexp
        sp-backward-unwrap-sexp
        sp-down-sexp
        sp-forward-sexp
        sp-kill-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        evil-normal-state
        hydra/projectile-tools/body
        ))
