;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        sp-backward-sexp
        sp-backward-unwrap-sexp
        sp-forward-sexp
        sp-kill-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
